language: java
jdk:
  - oraclejdk8
  - openjdk8
dist: trusty

addons:
  sonarcloud:
    organization: "lecousin"
    token:
      secure: Nyj3j9vYplwqTgkL3q9I/D+WrO0Y2vozAE9xn9v/zh6DD1/qReVRDXjW3R1oDnboFH5OrtkRotREtDZme7DjLFEsF3e8OcnNQg8hZD/ceoZVi66BmQTsT3KAdQ+xfQeW4AtSiHX4+SjrxAo3mUBQrf9/S/v6WXerAKv4aQrSLQhBkZC7/DbTc3mkF6aW31bS+EiM3Kb8HIYdUsShsoGnMWG+6K47wQJduDqtO2J+aXuQAXHR09pTvvQb5v9E53bM0DLYaUBY/LaZH11XHcTkp6W8ZEDg0x/Q96Kx7sqIhf5uGJfCRzUVEblPHRQ2jJsEb05ZDTj6iRd0LQY4fubeCeJkaB+vC8Y9HbOcI5ml5o4tB3zijgQ+GAWZvOEMAA1y3bXANi7wcMvocmc5xJBulvD7aiyLi9cb3MF6LxWc92+zkyg0zX5TkOTeFpRHMJ2r+gTDtXmH2CBh+w5Iize3MCPvkKxymdgh2WtgOMykXhzhFNSo72gpLFzZ6rlNzVEAe7IROyP7uU5N7jkAupW/aAc+HGQLas28KlwjQY9pvL1IAAfE1MB907E9DxOUiXhJoEffaBvKluCfn8rf41Z07sV/m8569eiY5JMh6TMhx/33eW4sxGgHPECPAGVUVIJcc5aFt07S37OwxbOu+iFswAFwcp3vwtVlRQXiNyo9/e8=

script: mvn test verify install sonar:sonar -Dsonar.projectKey=lecousin_java-framework-log-bridges -DprojectName=java-framework-log-bridges -B 
  
after_success:
 - bash <(curl -s https://codecov.io/bash)
